// LINK_ACTIONS
// export const FETCH_STORIES = 'FETCH_STORIES';
// export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
// export const FETCH_MORE_STORIES_SUCCESS = 'FETCH_MORE_STORIES_SUCCESS';
// export const FETCH_STORIES_FAILURE = 'FETCH_STORIES_FAILURE';

// export const REFRESH_STORIES = 'REFRESH_STORIES';
// export const REFRESH_STORIES_SUCCESS = 'REFRESH_STORIES_SUCCESS';
// export const REFRESH_STORIES_FAILURE = 'REFRESH_STORIES_FAILURE';

// export const FETCH_COMMENTS = 'FETCH_COMMENTS';
// export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
// export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';
// export const FETCH_MORE_COMMENTS_SUCCESS = 'FETCH_MORE_COMMENTS_SUCCESS';
// export const FETCH_COMMENTS_RESET = 'FETCH_COMMENTS_RESET';

// export const FAVORITE_STORY = 'FAVORITE_STORY';
// export const UNFAVORITE_STORY = 'UNFAVORITE_STORY';

// RECIPE ACTIONS
export const FETCH_RECIPE_DETAIL_REQUEST = 'FETCH_RECIPE_DETAIL_REQUEST';
export const FETCH_RECIPE_DETAIL_SUCCESS = 'FETCH_RECIPE_DETAIL_SUCCESS';
export const FETCH_RECIPE_DETAIL_FAILURE = 'FETCH_RECIPE_DETAIL_FAILURE';

export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';


export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_MOST_LIKED_RECIPES = 'GET_MOST_LIKED_RECIPES';
// export const GET_POPULAR_RECIPES = 'GET_POPULAR_RECIPES';
// export const GET_NEW_RECIPES = 'GET_NEW_RECIPES';

// SNACKBAR_ACTIONS
// export const DISPLAY_SNACKBAR = 'DISPLAY_SNACKBAR';
// export const HANDLE_CLOSE = 'HANDLE_CLOSE';

// ERROR_ACTIONS
export const RESET_ERRORS = 'RESET_ERRORS';
