// LINK_ACTIONS
export const GET_RECIPE = 'GET_RECIPE';
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_MOST_LIKED_RECIPES = 'GET_MOST_LIKED_RECIPES';
export const GET_POPULAR_RECIPES = 'GET_POPULAR_RECIPES';
export const GET_NEW_RECIPES = 'GET_NEW_RECIPES';

// SNACKBAR_ACTIONS
// export const DISPLAY_SNACKBAR = 'DISPLAY_SNACKBAR';
// export const HANDLE_CLOSE = 'HANDLE_CLOSE';

// ERROR_ACTIONS
export const RESET_ERRORS = 'RESET_ERRORS';
